name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Intall pip requirements
      run: pip install -r requirements.txt
    - name: Build the Docker image
      run: |
        cd dockerfile
        docker build -t ml:latest .
    - name: Run docker container
      run: docker run -d -p 5000:5000 ml
    - name: Run tests
      run: pytest -v
